### ISSUE TITLE
Empty matches table

### ISSUE THREAD

**Issue by gunnartorfis** [syxolk/euro2016#12]
Hi mate, thanks a lot for this decent web app. 

I've set it up and it's working great, but I don't have any matches to show and I checked the matches table and it's empty. Anything I'm missing here? I can log in, etc.

**Comment by syxolk** [comment]
Sry, I missed that in the README: You need to run this after installation to add all group matches:
(**This will also reset your database (delete all users and so on)**)

```
node tools/populate.js tools/euro2016.json
```

**Comment by gunnartorfis** [comment]
Thank you so much mate.

**Comment by syxolk** [comment]
Added hint in README with commit a1ff13f017f1a50985fddfee6b9240bb21441162.
