### ISSUE TITLE
score updates, pg problem, user management, package versions

### ISSUE THREAD

**Issue by zpo** [syxolk/euro2016#16]
Maybe it is a not an issue, rather some remarks and feedback.

I encountered a problem. Database was not able to connect (authorization: not valid password). I've changed 'pg' version in package.json to 5.0.0 - strange, but it helped.
I had also to change 'request' version to 2.69 and use the pull request with changed functions.sql.

I use node v.6.2.1, npm v.3.9.5, postgresql v9.5

How do you plan to update scores? Manual pull or automatic scrapping?

I think that simple user managemnt would be great.

Very important note: very great project :)

**Comment by gunnartorfis** [comment]
I was just going to ask about the scores as well. Surely there are loads of APIs out there that are free for mainstream football like the Euro competition.

Also, are you going to be calculating predicted round of 16 like this spreadsheet does? http://www.excely.com/football/euro-2016-schedule.shtml

Would be nice to get some points for predicting something like 16, 8, semi finals, finals and winner.

**Comment by syxolk** [comment]
> I had also to change 'request' version to 2.69 and use the pull request with changed functions.sql.

These version problems are pretty strange. I'm going to merge the PR regarding ¸functions.sql` today.

> How do you plan to update scores? Manual pull or automatic scrapping?

Sry, I didn't find any API that was for free AND seemed to be serious. However, there is an admin panel at `<your host>/admin` that allows *admins* to add matches and set results. There is an `admin` column in `User` table for this. But there is no user interface to set someone as admin, you have to do it in the database manually.

**Comment by zpo** [comment]
Maybe automatic update would be possible if using these components?
[football.api.js](https://github.com/footballjs/football.api.js)
[openfootball.db](https://github.com/openfootball/api)

Example: ```/event/euro.2016/round/today```

Maybe it is useful.

**Comment by zpo** [comment]
Of maybe [this one](http://api.football-data.org/register)?

**Comment by syxolk** [comment]
I might implement a parser for the official fifa worldcup 2018 page 😃
