### ISSUE TITLE
Saving bets

### ISSUE THREAD

**Issue by gunnartorfis** [syxolk/euro2016#17]
Some of my users are having issues with saving their bets, they don't get saved (when they refresh again, the bets are gone). I didn't have any issues myself though.

They do have Javascript endabled in their browser, so that's not the case. Any ideas?

**Comment by syxolk** [comment]
Nope, I've experienced this either.

There is a color animation in the text input indicating if saving was successful. It should be red whenever it fails to save.

**Comment by gunnartorfis** [comment]
Hmmm. The only reason I see why this could go wrong, is when one has Javascript disabled in his browser.

This doesn't make sense for me. They all have JS enabled and no network issues.

**Comment by syxolk** [comment]
There are at least 5 reasons the request can fail:
- User is not logged in
- Match already started (check your server time)
- Match not found (this should never be happening)
- Internal Database error (if there are severe problems with the database)
- HTTP error (request timed out or server unreachable)

For the Javascript problem: Can you ask them about their Browser and Browser version? Really old internet explorers may not be supported

**Comment by gunnartorfis** [comment]
Thanks for the super fast reply mate, really appreciate it. Hope this information helps:

* I'm assuming they're logged in since they can access the prediction view.
* My server time is Fri Jun 10 09:33:46 UTC 2016, still rougly 9 hours until the first match kick-off.
* Not the case
* /var/log/postgresql/postgresql-9.3-main.log doesn't give any hints
* It's hosted on a AWS EC2 instance, don't think that's the issue.

They both tried Chrome and Safari, not sure about versioning. They also tried on their mobile. I'll let you know when I know about their browsers' versions.

**Comment by gunnartorfis** [comment]
Browser version: Version 50.0.2661.102 (64-bit), running on El Capitan 10.11.4
Javascript is enabled

**Comment by gunnartorfis** [comment]
Another one.

Safari version 9.0.3
OS X Maverics 10.9.5
Javascript is enabled

**Comment by syxolk** [comment]
It would be really helpful to see the `Network` tab in the browser's developer tools (usually opened with `F12`) while making a bet.

**Comment by gunnartorfis** [comment]
Sorry for how long it took, just got a hold of the user.

![13396769_10154992595239358_89802381_o](https://cloud.githubusercontent.com/assets/5333875/15985636/cc4536f8-2fe3-11e6-8505-91af0e03bca0.png)

**Comment by syxolk** [comment]
There should be a `save_bet` request after inserting something in both text fields of one match.

**Comment by gunnartorfis** [comment]
Well, it's not being issued. Maybe a button that'd issue a regular http request (without JS), would do the trick?

**Comment by gunnartorfis** [comment]
After I pulled 29c027b99ead409b7959ae120e238e7096a679c5, this is no longer an issue. That commit is not what fixed it though, but I had an old commit.

I'm trying to update to the newest commit, but I'm just afraid about the database. How do I add the new columns without losing any data?

**Comment by gunnartorfis** [comment]
Any help you could provide me mate? I need to add the Match TV column.

**Comment by syxolk** [comment]
Execute this SQL: `alter table "Match" add column tv character varying(255)`
