### ISSUE TITLE
Starting from round of 16, how it will settle draw?

### ISSUE THREAD

**Issue by tuudik** [syxolk/euro2016#21]
If there is draw, then there will be penalties.
Is it possible to mark also who wins penalties?
How is the scoring then?

@AlexanderSachin Perhaps you have some good ideas too?

**Comment by syxolk** [comment]
I decided for wetten2016.de to include all goals that were scored during extratime (30 minutes) but to exclude the penalty goals at the very end. I will include this in the rules.

If you are hosting euro2016 yourself, you might have other ideas on how to handle this.

**Comment by tuudik** [comment]
Perhaps like this:
In UI under score input there would be radio buttons, that would activate when draw is predicted:
[ ] penalty goals [ ] 

Rule:
In case player predicted draw and chose correct team to win penalties, 3 points
In case player predicted draw and didnt not choose correct team to win penalties, 1 point?
