### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tuudik** [syxolk/euro2016#36]
Hi!
I see lots of activity in this repository.
Are You preparing for the FIFA2018?

**Comment by tuudik** [comment]
Do you have some planned date for release?

Awesome work btw!

**Comment by syxolk** [comment]
I'm currently cleaning up the code. It should be ready in one or two weeks.

**Comment by syxolk** [comment]
As you can see there are still open issues but the important things are implemented.

**Comment by tuudik** [comment]
Excellent job! I am already using it for month:) And updating all the time:)

I would suggest tho some small manual how to configure:) I use systemd for example to run it.

/lib/systemd/system/fifa2018.service
```[Unit]
Description=FIFA 2018 betting
After=network.target

[Service]
Type=simple
User=nodejs
Group= nodejs
WorkingDirectory=/srv/www/fifa/
ExecStart=/usr/bin/node /srv/www/fifa/index.js
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=fifa2018
Restart=on-failure
Environment=NODE_ENV=production
Environment=UTC_OFFSET=+0300
Environment=DB_USER=
Environment=DB_PASSWORD=
Environment=DB_HOST=localhost
Environment=DB_NAME=
Environment=DB_PORT=5432
Environment=SESSION_SECRET=octocat
Environment=ORIGIN=https://localhost
Environment=FACEBOOK_APP_ID=
Environment=FACEBOOK_APP_SECRET=
Environment=GOOGLE_APP_ID=
Environment=GOOGLE_APP_SECRET=
Environment=MAIL_SOLUTION=
Environment=MAILGUN_DOMAIN=
Environment=MAILGUN_API_KEY=
Environment=MAIL_FROM=
[Install]
WantedBy=multi-user.target```

**Comment by syxolk** [comment]
Probably not relevant anymore. I'm going to use docker this time.
