### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by mahyarx** [syxolk/euro2016#61]
after "sql: 'CREATE UNIQUE INDEX "bet__user_id__match_id" ON "Bet" ("UserId", "MatchId")' }" this line it will stop woking

**Comment by syxolk** [comment]
Do you get a specific error message?

**Comment by gunnartorfis** [comment]
I'm assuming you've ran
`node tools/populate.js tools/euro2016.json` (or with the world cup json file).

to populate the database. Clear/drop the database and just run
`node index.js`, Umzug will migrate for you.

**Comment by syxolk** [comment]
Probably not relevant anymore.
