### ISSUE TITLE
Change, how does it work?

### ISSUE THREAD

**Issue by tuudik** [syxolk/euro2016#67]
Hi! I dont understand what does the change show? Change from previous match or previous day matches? 

Also could you explain further how the position change number works? From previous position?
I doesnt seem to work properly, since I have case where previous first place owner dropped to second place, but it shows "+4"

**Comment by syxolk** [comment]
It's not super obvious to be honest. It takes the last match that has a match result and goes 24 hours back from there. The arrows (⬆️, ⬇️) and `Change` are computed from the same data.

There was also a bug in the highscore arrows and I fixed it today, see #66
