### ISSUE TITLE
Set Teams for future Matches, incorrect Match order

### ISSUE THREAD

**Issue by tuudik** [syxolk/euro2016#68]
When setting teams for future matches then select is not ordered correctly. I imagine it should be ordered by date, but currently I dont even understand what is used to order.

I tried to find the fix myself but my JS knowledge is too weak:)

**Comment by syxolk** [comment]
Thanks, I noticed that as well. I will fix it soon.

**Comment by syxolk** [comment]
It's fixed:

![image](https://user-images.githubusercontent.com/6666063/42100463-891094b0-7bc0-11e8-92d0-21979a67a0aa.png)

**Comment by tuudik** [comment]
Thx! works :)
